#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/Desktop/ALX_SSH-Key/school

# Username and IP Address 
ssh ubuntu@52.90.14.216
